name: github pages

on:
  push:
    branches:
      - main
      - master
      - add-nimibook-docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v3
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-stable

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('karax.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1.4.5
        with:
          nim-version: devel

      - name: Install Packages
        run: nimble install -y

      - name: Build docs
        run: nimble --verbose docs

      - name: Archive docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            docs/dist

  deploy-docs:
    needs:
      - docs
    runs-on: ubuntu-latest
    steps:
      - name: Download all docs
        uses: actions/download-artifact@v3

      - name: Check files
        run: |
          find .

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
